modLoader = "javafml"
loaderVersion = "[47,48)"
license = "MIT"

[[mods]]
modId = "simplysmith"
version = "${version}"
displayName = "CJiangqiu's SimplySmith"
authors = "CJiangqiu"
description = '''Adds gear quality, random affixes, enhancement, and quality breakthroughs.'''
logoFile = "assets/simplysmith/icon.png"

[[dependencies.simplysmith]]
modId = "forge"
mandatory = true
versionRange = "[47,48)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplysmith]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.simplysmith]]
modId = "cloth_config"
mandatory = false
versionRange = "[11,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.simplysmith]]
modId = "jei"
mandatory = false
versionRange = "[15,)"
ordering = "AFTER"
side = "CLIENT"
