# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.5
maven_group = net.simplysmith
archives_name = simplysmith
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
fabric_loader_version = 0.19.3
fabric_api_version = 0.92.11+1.20.1
forge_version = 1.20.1-47.4.22
cloth_config_version = 11.1.136
modmenu_version = 7.2.2
jei_version = 15.20.0.106
