architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // 仅用于编译可选配置页面，不会打包进 SimplySmith，也不是运行必需项
    modCompileOnly "me.shedaniel.cloth:cloth-config:$rootProject.cloth_config_version"

    // 同上，仅用于编译可选的 JEI 插件
    modCompileOnly "mezz.jei:jei-$rootProject.minecraft_version-common-api:$rootProject.jei_version"
}
